In [4]:
import pandas as pd

app = pd.read_csv(r"C:\Users\Saksham\OneDrive\Desktop\credit-risk-analytics\data\application_train.csv")
bureau = pd.read_csv(r"C:\Users\Saksham\OneDrive\Desktop\credit-risk-analytics\data\bureau.csv")
prev = pd.read_csv(r"C:\Users\Saksham\OneDrive\Desktop\credit-risk-analytics\data\previous_application.csv")

print(app.shape)
print(bureau.shape)
print(prev.shape)

print(app.head())

(307511, 122)
(1716428, 17)
(1670214, 37)
   SK_ID_CURR  TARGET NAME_CONTRACT_TYPE CODE_GENDER FLAG_OWN_CAR  \
0      100002       1         Cash loans           M            N
1      100003       0         Cash loans           F            N
2      100004       0    Revolving loans           M            Y
3      100006       0         Cash loans           F            N
4      100007       0         Cash loans           M            N

  FLAG_OWN_REALTY  CNT_CHILDREN  AMT_INCOME_TOTAL  AMT_CREDIT  AMT_ANNUITY  \
0               Y             0          202500.0    406597.5      24700.5
1               N             0          270000.0   1293502.5      35698.5
2               Y             0           67500.0    135000.0       6750.0
3               Y             0          135000.0    312682.5      29686.5
4               Y             0          121500.0    513000.0      21865.5

   ...  FLAG_DOCUMENT_18 FLAG_DOCUMENT_19 FLAG_DOCUMENT_20 FLAG_DOCUMENT_21  \
0  ...                 0                0                0                0
1  ...                 0                0                0                0
2  ...                 0                0                0                0
3  ...                 0                0                0                0
4  ...                 0                0                0                0

  AMT_REQ_CREDIT_BUREAU_HOUR AMT_REQ_CREDIT_BUREAU_DAY  \
0                        0.0                       0.0
1                        0.0                       0.0
2                        0.0                       0.0
3                        NaN                       NaN
4                        0.0                       0.0

   AMT_REQ_CREDIT_BUREAU_WEEK  AMT_REQ_CREDIT_BUREAU_MON  \
0                         0.0                        0.0
1                         0.0                        0.0
2                         0.0                        0.0
3                         NaN                        NaN
4                         0.0                        0.0

   AMT_REQ_CREDIT_BUREAU_QRT  AMT_REQ_CREDIT_BUREAU_YEAR
0                        0.0                         1.0
1                        0.0                         0.0
2                        0.0                         0.0
3                        NaN                         NaN
4                        0.0                         0.0

[5 rows x 122 columns]

In [5]:
print(app.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 307511 entries, 0 to 307510
Columns: 122 entries, SK_ID_CURR to AMT_REQ_CREDIT_BUREAU_YEAR
dtypes: float64(65), int64(41), object(16)
memory usage: 286.2+ MB
None

In [6]:
missing = (
    app.isnull()
       .sum()
       .sort_values(ascending=False)
)

print(missing.head(20))

COMMONAREA_AVG              214865
COMMONAREA_MODE             214865
COMMONAREA_MEDI             214865
NONLIVINGAPARTMENTS_MEDI    213514
NONLIVINGAPARTMENTS_MODE    213514
NONLIVINGAPARTMENTS_AVG     213514
FONDKAPREMONT_MODE          210295
LIVINGAPARTMENTS_AVG        210199
LIVINGAPARTMENTS_MEDI       210199
LIVINGAPARTMENTS_MODE       210199
FLOORSMIN_MODE              208642
FLOORSMIN_AVG               208642
FLOORSMIN_MEDI              208642
YEARS_BUILD_AVG             204488
YEARS_BUILD_MODE            204488
YEARS_BUILD_MEDI            204488
OWN_CAR_AGE                 202929
LANDAREA_MEDI               182590
LANDAREA_AVG                182590
LANDAREA_MODE               182590
dtype: int64

In [7]:
missing_pct = (
    app.isnull()
       .mean()
       .mul(100)
       .sort_values(ascending=False)
)

print(missing_pct.head(30))

COMMONAREA_AVG              69.872297
COMMONAREA_MODE             69.872297
COMMONAREA_MEDI             69.872297
NONLIVINGAPARTMENTS_MEDI    69.432963
NONLIVINGAPARTMENTS_MODE    69.432963
NONLIVINGAPARTMENTS_AVG     69.432963
FONDKAPREMONT_MODE          68.386172
LIVINGAPARTMENTS_AVG        68.354953
LIVINGAPARTMENTS_MEDI       68.354953
LIVINGAPARTMENTS_MODE       68.354953
FLOORSMIN_MODE              67.848630
FLOORSMIN_AVG               67.848630
FLOORSMIN_MEDI              67.848630
YEARS_BUILD_AVG             66.497784
YEARS_BUILD_MODE            66.497784
YEARS_BUILD_MEDI            66.497784
OWN_CAR_AGE                 65.990810
LANDAREA_MEDI               59.376738
LANDAREA_AVG                59.376738
LANDAREA_MODE               59.376738
BASEMENTAREA_MODE           58.515956
BASEMENTAREA_MEDI           58.515956
BASEMENTAREA_AVG            58.515956
EXT_SOURCE_1                56.381073
NONLIVINGAREA_MODE          55.179164
NONLIVINGAREA_AVG           55.179164
NONLIVINGAREA_MEDI          55.179164
ELEVATORS_AVG               53.295980
ELEVATORS_MEDI              53.295980
ELEVATORS_MODE              53.295980
dtype: float64

In [8]:
print(app['TARGET'].value_counts())
print(app['TARGET'].value_counts(normalize=True)*100)

TARGET
0    282686
1     24825
Name: count, dtype: int64
TARGET
0    91.927118
1     8.072882
Name: proportion, dtype: float64

In [9]:
print(app.columns.tolist())

['SK_ID_CURR', 'TARGET', 'NAME_CONTRACT_TYPE', 'CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'CNT_CHILDREN', 'AMT_INCOME_TOTAL', 'AMT_CREDIT', 'AMT_ANNUITY', 'AMT_GOODS_PRICE', 'NAME_TYPE_SUITE', 'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE', 'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE', 'REGION_POPULATION_RELATIVE', 'DAYS_BIRTH', 'DAYS_EMPLOYED', 'DAYS_REGISTRATION', 'DAYS_ID_PUBLISH', 'OWN_CAR_AGE', 'FLAG_MOBIL', 'FLAG_EMP_PHONE', 'FLAG_WORK_PHONE', 'FLAG_CONT_MOBILE', 'FLAG_PHONE', 'FLAG_EMAIL', 'OCCUPATION_TYPE', 'CNT_FAM_MEMBERS', 'REGION_RATING_CLIENT', 'REGION_RATING_CLIENT_W_CITY', 'WEEKDAY_APPR_PROCESS_START', 'HOUR_APPR_PROCESS_START', 'REG_REGION_NOT_LIVE_REGION', 'REG_REGION_NOT_WORK_REGION', 'LIVE_REGION_NOT_WORK_REGION', 'REG_CITY_NOT_LIVE_CITY', 'REG_CITY_NOT_WORK_CITY', 'LIVE_CITY_NOT_WORK_CITY', 'ORGANIZATION_TYPE', 'EXT_SOURCE_1', 'EXT_SOURCE_2', 'EXT_SOURCE_3', 'APARTMENTS_AVG', 'BASEMENTAREA_AVG', 'YEARS_BEGINEXPLUATATION_AVG', 'YEARS_BUILD_AVG', 'COMMONAREA_AVG', 'ELEVATORS_AVG', 'ENTRANCES_AVG', 'FLOORSMAX_AVG', 'FLOORSMIN_AVG', 'LANDAREA_AVG', 'LIVINGAPARTMENTS_AVG', 'LIVINGAREA_AVG', 'NONLIVINGAPARTMENTS_AVG', 'NONLIVINGAREA_AVG', 'APARTMENTS_MODE', 'BASEMENTAREA_MODE', 'YEARS_BEGINEXPLUATATION_MODE', 'YEARS_BUILD_MODE', 'COMMONAREA_MODE', 'ELEVATORS_MODE', 'ENTRANCES_MODE', 'FLOORSMAX_MODE', 'FLOORSMIN_MODE', 'LANDAREA_MODE', 'LIVINGAPARTMENTS_MODE', 'LIVINGAREA_MODE', 'NONLIVINGAPARTMENTS_MODE', 'NONLIVINGAREA_MODE', 'APARTMENTS_MEDI', 'BASEMENTAREA_MEDI', 'YEARS_BEGINEXPLUATATION_MEDI', 'YEARS_BUILD_MEDI', 'COMMONAREA_MEDI', 'ELEVATORS_MEDI', 'ENTRANCES_MEDI', 'FLOORSMAX_MEDI', 'FLOORSMIN_MEDI', 'LANDAREA_MEDI', 'LIVINGAPARTMENTS_MEDI', 'LIVINGAREA_MEDI', 'NONLIVINGAPARTMENTS_MEDI', 'NONLIVINGAREA_MEDI', 'FONDKAPREMONT_MODE', 'HOUSETYPE_MODE', 'TOTALAREA_MODE', 'WALLSMATERIAL_MODE', 'EMERGENCYSTATE_MODE', 'OBS_30_CNT_SOCIAL_CIRCLE', 'DEF_30_CNT_SOCIAL_CIRCLE', 'OBS_60_CNT_SOCIAL_CIRCLE', 'DEF_60_CNT_SOCIAL_CIRCLE', 'DAYS_LAST_PHONE_CHANGE', 'FLAG_DOCUMENT_2', 'FLAG_DOCUMENT_3', 'FLAG_DOCUMENT_4', 'FLAG_DOCUMENT_5', 'FLAG_DOCUMENT_6', 'FLAG_DOCUMENT_7', 'FLAG_DOCUMENT_8', 'FLAG_DOCUMENT_9', 'FLAG_DOCUMENT_10', 'FLAG_DOCUMENT_11', 'FLAG_DOCUMENT_12', 'FLAG_DOCUMENT_13', 'FLAG_DOCUMENT_14', 'FLAG_DOCUMENT_15', 'FLAG_DOCUMENT_16', 'FLAG_DOCUMENT_17', 'FLAG_DOCUMENT_18', 'FLAG_DOCUMENT_19', 'FLAG_DOCUMENT_20', 'FLAG_DOCUMENT_21', 'AMT_REQ_CREDIT_BUREAU_HOUR', 'AMT_REQ_CREDIT_BUREAU_DAY', 'AMT_REQ_CREDIT_BUREAU_WEEK', 'AMT_REQ_CREDIT_BUREAU_MON', 'AMT_REQ_CREDIT_BUREAU_QRT', 'AMT_REQ_CREDIT_BUREAU_YEAR']

In [11]:
desc = pd.read_csv(
    r"C:\Users\Saksham\OneDrive\Desktop\credit-risk-analytics\data\HomeCredit_columns_description.csv",
    encoding='latin1'
)

print(desc.head())
print(desc.columns)

   Unnamed: 0                         Table                 Row  \
0           1  application_{train|test}.csv          SK_ID_CURR
1           2  application_{train|test}.csv              TARGET
2           5  application_{train|test}.csv  NAME_CONTRACT_TYPE
3           6  application_{train|test}.csv         CODE_GENDER
4           7  application_{train|test}.csv        FLAG_OWN_CAR

                                         Description Special
0                           ID of loan in our sample     NaN
1  Target variable (1 - client with payment diffi...     NaN
2        Identification if loan is cash or revolving     NaN
3                               Gender of the client     NaN
4                      Flag if the client owns a car     NaN
Index(['Unnamed: 0', 'Table', 'Row', 'Description', 'Special'], dtype='object')

In [12]:
print(desc.shape)

(219, 5)

In [13]:
desc.head(20)

,Unnamed: 0,Table,Row,Description,Special
0,1,application_{train|test}.csv,SK_ID_CURR,ID of loan in our sample,NaN
1,2,application_{train|test}.csv,TARGET,Target variable (1 - client with payment diffi...,NaN
2,5,application_{train|test}.csv,NAME_CONTRACT_TYPE,Identification if loan is cash or revolving,NaN
3,6,application_{train|test}.csv,CODE_GENDER,Gender of the client,NaN
4,7,application_{train|test}.csv,FLAG_OWN_CAR,Flag if the client owns a car,NaN
5,8,application_{train|test}.csv,FLAG_OWN_REALTY,Flag if client owns a house or flat,NaN
6,9,application_{train|test}.csv,CNT_CHILDREN,Number of children the client has,NaN
7,10,application_{train|test}.csv,AMT_INCOME_TOTAL,Income of the client,NaN
8,11,application_{train|test}.csv,AMT_CREDIT,Credit amount of the loan,NaN
9,12,application_{train|test}.csv,AMT_ANNUITY,Loan annuity,NaN
10,13,application_{train|test}.csv,AMT_GOODS_PRICE,For consumer loans it is the price of the good...,NaN
11,14,application_{train|test}.csv,NAME_TYPE_SUITE,Who was accompanying client when he was applyi...,NaN
12,15,application_{train|test}.csv,NAME_INCOME_TYPE,"Clients income type (businessman, working, mat...",NaN
13,16,application_{train|test}.csv,NAME_EDUCATION_TYPE,Level of highest education the client achieved,NaN
14,17,application_{train|test}.csv,NAME_FAMILY_STATUS,Family status of the client,NaN
15,18,application_{train|test}.csv,NAME_HOUSING_TYPE,What is the housing situation of the client (r...,NaN
16,19,application_{train|test}.csv,REGION_POPULATION_RELATIVE,Normalized population of region where client l...,normalized
17,20,application_{train|test}.csv,DAYS_BIRTH,Client's age in days at the time of application,time only relative to the application
18,21,application_{train|test}.csv,DAYS_EMPLOYED,How many days before the application the perso...,time only relative to the application
19,22,application_{train|test}.csv,DAYS_REGISTRATION,How many days before the application did clien...,time only relative to the application

In [14]:
desc[desc['Row'].str.contains('EXT_SOURCE', na=False)]

,Unnamed: 0,Table,Row,Description,Special
41,44,application_{train|test}.csv,EXT_SOURCE_1,Normalized score from external data source,normalized
42,45,application_{train|test}.csv,EXT_SOURCE_2,Normalized score from external data source,normalized
43,46,application_{train|test}.csv,EXT_SOURCE_3,Normalized score from external data source,normalized

In [15]:
desc['Table'].value_counts()

Table
application_{train|test}.csv    122
previous_application.csv         38
credit_card_balance.csv          23
bureau.csv                       17
POS_CASH_balance.csv              8
installments_payments.csv         8
bureau_balance.csv                3
Name: count, dtype: int64

In [17]:
desc[
    desc['Table'].str.contains('application', na=False)
][['Row', 'Description']].head(50)

,Row,Description
0,SK_ID_CURR,ID of loan in our sample
1,TARGET,Target variable (1 - client with payment diffi...
2,NAME_CONTRACT_TYPE,Identification if loan is cash or revolving
3,CODE_GENDER,Gender of the client
4,FLAG_OWN_CAR,Flag if the client owns a car
5,FLAG_OWN_REALTY,Flag if client owns a house or flat
6,CNT_CHILDREN,Number of children the client has
7,AMT_INCOME_TOTAL,Income of the client
8,AMT_CREDIT,Credit amount of the loan
9,AMT_ANNUITY,Loan annuity
10,AMT_GOODS_PRICE,For consumer loans it is the price of the good...
11,NAME_TYPE_SUITE,Who was accompanying client when he was applyi...
12,NAME_INCOME_TYPE,"Clients income type (businessman, working, mat..."
13,NAME_EDUCATION_TYPE,Level of highest education the client achieved
14,NAME_FAMILY_STATUS,Family status of the client
15,NAME_HOUSING_TYPE,What is the housing situation of the client (r...
16,REGION_POPULATION_RELATIVE,Normalized population of region where client l...
17,DAYS_BIRTH,Client's age in days at the time of application
18,DAYS_EMPLOYED,How many days before the application the perso...
19,DAYS_REGISTRATION,How many days before the application did clien...
20,DAYS_ID_PUBLISH,How many days before the application did clien...
21,OWN_CAR_AGE,Age of client's car
22,FLAG_MOBIL,"Did client provide mobile phone (1=YES, 0=NO)"
23,FLAG_EMP_PHONE,"Did client provide work phone (1=YES, 0=NO)"
24,FLAG_WORK_PHONE,"Did client provide home phone (1=YES, 0=NO)"
25,FLAG_CONT_MOBILE,"Was mobile phone reachable (1=YES, 0=NO)"
26,FLAG_PHONE,"Did client provide home phone (1=YES, 0=NO)"
27,FLAG_EMAIL,"Did client provide email (1=YES, 0=NO)"
28,OCCUPATION_TYPE,What kind of occupation does the client have
29,CNT_FAM_MEMBERS,How many family members does client have
30,REGION_RATING_CLIENT,Our rating of the region where client lives (1...
31,REGION_RATING_CLIENT_W_CITY,Our rating of the region where client lives wi...
32,WEEKDAY_APPR_PROCESS_START,On which day of the week did the client apply ...
33,HOUR_APPR_PROCESS_START,Approximately at what hour did the client appl...
34,REG_REGION_NOT_LIVE_REGION,Flag if client's permanent address does not ma...
35,REG_REGION_NOT_WORK_REGION,Flag if client's permanent address does not ma...
36,LIVE_REGION_NOT_WORK_REGION,Flag if client's contact address does not matc...
37,REG_CITY_NOT_LIVE_CITY,Flag if client's permanent address does not ma...
38,REG_CITY_NOT_WORK_CITY,Flag if client's permanent address does not ma...
39,LIVE_CITY_NOT_WORK_CITY,Flag if client's contact address does not matc...
40,ORGANIZATION_TYPE,Type of organization where client works
41,EXT_SOURCE_1,Normalized score from external data source
42,EXT_SOURCE_2,Normalized score from external data source
43,EXT_SOURCE_3,Normalized score from external data source
44,APARTMENTS_AVG,Normalized information about building where th...
45,BASEMENTAREA_AVG,Normalized information about building where th...
46,YEARS_BEGINEXPLUATATION_AVG,Normalized information about building where th...
47,YEARS_BUILD_AVG,Normalized information about building where th...
48,COMMONAREA_AVG,Normalized information about building where th...
49,ELEVATORS_AVG,Normalized information about building where th...

In [18]:
desc[
    desc['Table'].str.contains('bureau', na=False)
][['Row', 'Description']]

                        Row                                        Description
122              SK_ID_CURR  ID of loan in our sample - one loan in our sam...
123            SK_BUREAU_ID  Recoded ID of previous Credit Bureau credit re...
124           CREDIT_ACTIVE  Status of the Credit Bureau (CB) reported credits
125         CREDIT_CURRENCY       Recoded currency of the Credit Bureau credit
126             DAYS_CREDIT  How many days before current application did c...
127      CREDIT_DAY_OVERDUE  Number of days past due on CB credit at the ti...
128     DAYS_CREDIT_ENDDATE  Remaining duration of CB credit (in days) at t...
129       DAYS_ENDDATE_FACT  Days since CB credit ended at the time of appl...
130  AMT_CREDIT_MAX_OVERDUE  Maximal amount overdue on the Credit Bureau cr...
131      CNT_CREDIT_PROLONG  How many times was the Credit Bureau credit pr...
132          AMT_CREDIT_SUM  Current credit amount for the Credit Bureau cr...
133     AMT_CREDIT_SUM_DEBT               Current debt on Credit Bureau credit
134    AMT_CREDIT_SUM_LIMIT  Current credit limit of credit card reported i...
135  AMT_CREDIT_SUM_OVERDUE     Current amount overdue on Credit Bureau credit
136             CREDIT_TYPE       Type of Credit Bureau credit (Car, cash,...)
137      DAYS_CREDIT_UPDATE  How many days before loan application did last...
138             AMT_ANNUITY                Annuity of the Credit Bureau credit
139            SK_BUREAU_ID  Recoded ID of Credit Bureau credit (unique cod...
140          MONTHS_BALANCE  Month of balance relative to application date ...
141                  STATUS  Status of Credit Bureau loan during the month ...

In [19]:
desc[
    desc['Table'].str.contains('previous_application', na=False)
][['Row', 'Description']]

,Row,Description
173,SK_ID_PREV,ID of previous credit in Home credit related t...
174,SK_ID_CURR,ID of loan in our sample
175,NAME_CONTRACT_TYPE,"Contract product type (Cash loan, consumer loa..."
176,AMT_ANNUITY,Annuity of previous application
177,AMT_APPLICATION,For how much credit did client ask on the prev...
178,AMT_CREDIT,Final credit amount on the previous applicatio...
179,AMT_DOWN_PAYMENT,Down payment on the previous application
180,AMT_GOODS_PRICE,Goods price of good that client asked for (if ...
181,WEEKDAY_APPR_PROCESS_START,On which day of the week did the client apply ...
182,HOUR_APPR_PROCESS_START,Approximately at what day hour did the client ...
183,FLAG_LAST_APPL_PER_CONTRACT,Flag if it was last application for the previo...
184,NFLAG_LAST_APPL_IN_DAY,Flag if the application was the last applicati...
185,NFLAG_MICRO_CASH,Flag Micro finance loan
186,RATE_DOWN_PAYMENT,Down payment rate normalized on previous credit
187,RATE_INTEREST_PRIMARY,Interest rate normalized on previous credit
188,RATE_INTEREST_PRIVILEGED,Interest rate normalized on previous credit
189,NAME_CASH_LOAN_PURPOSE,Purpose of the cash loan
190,NAME_CONTRACT_STATUS,"Contract status (approved, cancelled, ...) of ..."
191,DAYS_DECISION,Relative to current application when was the d...
192,NAME_PAYMENT_TYPE,Payment method that client chose to pay for th...
193,CODE_REJECT_REASON,Why was the previous application rejected
194,NAME_TYPE_SUITE,Who accompanied client when applying for the p...
195,NAME_CLIENT_TYPE,Was the client old or new client when applying...
196,NAME_GOODS_CATEGORY,What kind of goods did the client apply for in...
197,NAME_PORTFOLIO,"Was the previous application for CASH, POS, CA..."
198,NAME_PRODUCT_TYPE,Was the previous application x-sell o walk-in
199,CHANNEL_TYPE,Through which channel we acquired the client o...
200,SELLERPLACE_AREA,Selling area of seller place of the previous a...
201,NAME_SELLER_INDUSTRY,The industry of the seller
202,CNT_PAYMENT,Term of previous credit at application of the ...
203,NAME_YIELD_GROUP,Grouped interest rate into small medium and hi...
204,PRODUCT_COMBINATION,Detailed product combination of the previous a...
205,DAYS_FIRST_DRAWING,Relative to application date of current applic...
206,DAYS_FIRST_DUE,Relative to application date of current applic...
207,DAYS_LAST_DUE_1ST_VERSION,Relative to application date of current applic...
208,DAYS_LAST_DUE,Relative to application date of current applic...
209,DAYS_TERMINATION,Relative to application date of current applic...
210,NFLAG_INSURED_ON_APPROVAL,Did the client requested insurance during the ...

In [24]:
print("Application:", app['SK_ID_CURR'].nunique())
print("Bureau:", bureau['SK_ID_CURR'].nunique())
print("Previous:", prev['SK_ID_CURR'].nunique())

Application: 307511
Bureau: 305811
Previous: 338857

In [21]:
bureau.groupby('SK_ID_CURR').size().describe()

prev.groupby('SK_ID_CURR').size().describe()

count    338857.000000
mean          4.928964
std           4.220716
min           1.000000
25%           2.000000
50%           4.000000
75%           7.000000
max          77.000000
dtype: float64

In [23]:
prev.groupby('SK_ID_CURR').size().describe()

count    338857.000000
mean          4.928964
std           4.220716
min           1.000000
25%           2.000000
50%           4.000000
75%           7.000000
max          77.000000
dtype: float64

In [25]:
important_cols = [
    'TARGET',
    'AMT_INCOME_TOTAL',
    'AMT_CREDIT',
    'AMT_ANNUITY',
    'EXT_SOURCE_1',
    'EXT_SOURCE_2',
    'EXT_SOURCE_3',
    'DAYS_BIRTH',
    'DAYS_EMPLOYED'
]

app[important_cols].isnull().mean()*100

TARGET               0.000000
AMT_INCOME_TOTAL     0.000000
AMT_CREDIT           0.000000
AMT_ANNUITY          0.003902
EXT_SOURCE_1        56.381073
EXT_SOURCE_2         0.214626
EXT_SOURCE_3        19.825307
DAYS_BIRTH           0.000000
DAYS_EMPLOYED        0.000000
dtype: float64

In [26]:
app.groupby('TARGET')[
    ['EXT_SOURCE_1','EXT_SOURCE_2','EXT_SOURCE_3']
].mean()

        EXT_SOURCE_1  EXT_SOURCE_2  EXT_SOURCE_3
TARGET
0           0.511461      0.523479      0.520969
1           0.386968      0.410935      0.390717

In [27]:
app[
    ['AMT_INCOME_TOTAL',
     'AMT_CREDIT',
     'AMT_ANNUITY',
     'DAYS_BIRTH',
     'DAYS_EMPLOYED']
].describe()

,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,DAYS_BIRTH,DAYS_EMPLOYED
count,3.075110e+05,3.075110e+05,307499.000000,307511.000000,307511.000000
mean,1.687979e+05,5.990260e+05,27108.573909,-16036.995067,63815.045904
std,2.371231e+05,4.024908e+05,14493.737315,4363.988632,141275.766519
min,2.565000e+04,4.500000e+04,1615.500000,-25229.000000,-17912.000000
25%,1.125000e+05,2.700000e+05,16524.000000,-19682.000000,-2760.000000
50%,1.471500e+05,5.135310e+05,24903.000000,-15750.000000,-1213.000000
75%,2.025000e+05,8.086500e+05,34596.000000,-12413.000000,-289.000000
max,1.170000e+08,4.050000e+06,258025.500000,-7489.000000,365243.000000

In [28]:
bureau_summary = bureau.groupby('SK_ID_CURR').agg(
    total_bureau_records=('SK_ID_BUREAU', 'count'),
    total_credit_sum=('AMT_CREDIT_SUM', 'sum'),
    total_debt=('AMT_CREDIT_SUM_DEBT', 'sum'),
    total_overdue=('AMT_CREDIT_SUM_OVERDUE', 'sum'),
    max_overdue=('AMT_CREDIT_MAX_OVERDUE', 'max')
).reset_index()

bureau_summary.head()

,SK_ID_CURR,total_bureau_records,total_credit_sum,total_debt,total_overdue,max_overdue
0,100001,7,1453365.000,596686.5,0.0,NaN
1,100002,8,865055.565,245781.0,0.0,5043.645
2,100003,4,1017400.500,0.0,0.0,0.000
3,100004,2,189037.800,0.0,0.0,0.000
4,100005,3,657126.000,568408.5,0.0,0.000

In [29]:
prev_summary = prev.groupby('SK_ID_CURR').agg(
    total_previous_apps=('SK_ID_PREV', 'count'),
    avg_prev_credit=('AMT_CREDIT', 'mean'),
    avg_prev_application=('AMT_APPLICATION', 'mean')
).reset_index()

prev_summary.head()

   SK_ID_CURR  total_previous_apps  avg_prev_credit  avg_prev_application
0      100001                    1         23787.00              24835.50
1      100002                    1        179055.00             179055.00
2      100003                    3        484191.00             435436.50
3      100004                    1         20106.00              24282.00
4      100005                    2         20076.75              22308.75

In [30]:
customer_master = app[
    [
        'SK_ID_CURR',
        'TARGET',
        'CODE_GENDER',
        'DAYS_BIRTH',
        'AMT_INCOME_TOTAL',
        'AMT_CREDIT',
        'AMT_ANNUITY',
        'EXT_SOURCE_1',
        'EXT_SOURCE_2',
        'EXT_SOURCE_3'
    ]
]

In [31]:
analytics_df = (
    customer_master
    .merge(bureau_summary, on='SK_ID_CURR', how='left')
    .merge(prev_summary, on='SK_ID_CURR', how='left')
)

In [32]:
analytics_df.shape

(307511, 18)

In [33]:
analytics_df.head()

,SK_ID_CURR,TARGET,CODE_GENDER,DAYS_BIRTH,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,total_bureau_records,total_credit_sum,total_debt,total_overdue,max_overdue,total_previous_apps,avg_prev_credit,avg_prev_application
0,100002,1,M,-9461,202500.0,406597.5,24700.5,0.083037,0.262949,0.139376,8.0,865055.565,245781.0,0.0,5043.645,1.0,179055.00,179055.00
1,100003,0,F,-16765,270000.0,1293502.5,35698.5,0.311267,0.622246,NaN,4.0,1017400.500,0.0,0.0,0.000,3.0,484191.00,435436.50
2,100004,0,M,-19046,67500.0,135000.0,6750.0,NaN,0.555912,0.729567,2.0,189037.800,0.0,0.0,0.000,1.0,20106.00,24282.00
3,100006,0,F,-19005,135000.0,312682.5,29686.5,NaN,0.650442,NaN,NaN,NaN,NaN,NaN,NaN,9.0,291695.50,272203.26
4,100007,0,M,-19932,121500.0,513000.0,21865.5,NaN,0.322738,NaN,1.0,146250.000,0.0,0.0,0.000,6.0,166638.75,150530.25

In [34]:
analytics_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 307511 entries, 0 to 307510
Data columns (total 18 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   SK_ID_CURR            307511 non-null  int64
 1   TARGET                307511 non-null  int64
 2   CODE_GENDER           307511 non-null  object
 3   DAYS_BIRTH            307511 non-null  int64
 4   AMT_INCOME_TOTAL      307511 non-null  float64
 5   AMT_CREDIT            307511 non-null  float64
 6   AMT_ANNUITY           307499 non-null  float64
 7   EXT_SOURCE_1          134133 non-null  float64
 8   EXT_SOURCE_2          306851 non-null  float64
 9   EXT_SOURCE_3          246546 non-null  float64
 10  total_bureau_records  263491 non-null  float64
 11  total_credit_sum      263491 non-null  float64
 12  total_debt            263491 non-null  float64
 13  total_overdue         263491 non-null  float64
 14  max_overdue           183886 non-null  float64
 15  total_previous_apps   291057 non-null  float64
 16  avg_prev_credit       291057 non-null  float64
 17  avg_prev_application  291057 non-null  float64
dtypes: float64(14), int64(3), object(1)
memory usage: 42.2+ MB

In [35]:
analytics_df['AGE_YEARS'] = (
    analytics_df['DAYS_BIRTH'].abs() / 365
).round(1)

In [37]:
customer_master = app[
[
    'SK_ID_CURR',
    'TARGET',
    'CODE_GENDER',
    'DAYS_BIRTH',
    'DAYS_EMPLOYED',
    'AMT_INCOME_TOTAL',
    'AMT_CREDIT',
    'AMT_ANNUITY',
    'EXT_SOURCE_1',
    'EXT_SOURCE_2',
    'EXT_SOURCE_3'
]
]

In [38]:
analytics_df = (
    customer_master
    .merge(bureau_summary, on='SK_ID_CURR', how='left')
    .merge(prev_summary, on='SK_ID_CURR', how='left')
)

In [39]:
analytics_df['DAYS_EMPLOYED'] = (
    analytics_df['DAYS_EMPLOYED']
    .replace(365243, pd.NA)
)

In [40]:
analytics_df.to_csv(
    "analytics_customer.csv",
    index=False
)

In [41]:
analytics_df.shape
analytics_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 307511 entries, 0 to 307510
Data columns (total 19 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   SK_ID_CURR            307511 non-null  int64
 1   TARGET                307511 non-null  int64
 2   CODE_GENDER           307511 non-null  object
 3   DAYS_BIRTH            307511 non-null  int64
 4   DAYS_EMPLOYED         252137 non-null  object
 5   AMT_INCOME_TOTAL      307511 non-null  float64
 6   AMT_CREDIT            307511 non-null  float64
 7   AMT_ANNUITY           307499 non-null  float64
 8   EXT_SOURCE_1          134133 non-null  float64
 9   EXT_SOURCE_2          306851 non-null  float64
 10  EXT_SOURCE_3          246546 non-null  float64
 11  total_bureau_records  263491 non-null  float64
 12  total_credit_sum      263491 non-null  float64
 13  total_debt            263491 non-null  float64
 14  total_overdue         263491 non-null  float64
 15  max_overdue           183886 non-null  float64
 16  total_previous_apps   291057 non-null  float64
 17  avg_prev_credit       291057 non-null  float64
 18  avg_prev_application  291057 non-null  float64
dtypes: float64(14), int64(3), object(2)
memory usage: 44.6+ MB

In [42]:
analytics_df['DAYS_EMPLOYED'].max()

0

In [44]:
analytics_df['DAYS_EMPLOYED'] = pd.to_numeric(
    analytics_df['DAYS_EMPLOYED'],
    errors='coerce'
)

In [45]:
analytics_df['DAYS_EMPLOYED'].dtype

dtype('float64')

In [46]:
analytics_df['DAYS_EMPLOYED'].max()

np.float64(0.0)

In [47]:
'AGE_YEARS' in analytics_df.columns

False

In [48]:
analytics_df['AGE_YEARS'] = (
    analytics_df['DAYS_BIRTH'].abs() / 365
).round(1)

In [49]:
analytics_df.to_csv(
    "analytics_customer.csv",
    index=False
)

In [50]:
analytics_df['DAYS_EMPLOYED'].describe()

count    252137.000000
mean      -2384.169325
std        2338.360162
min      -17912.000000
25%       -3175.000000
50%       -1648.000000
75%        -767.000000
max           0.000000
Name: DAYS_EMPLOYED, dtype: float64

In [51]:
analytics_df['DAYS_EMPLOYED'].head(10)

0    -637.0
1   -1188.0
2    -225.0
3   -3039.0
4   -3038.0
5   -1588.0
6   -3130.0
7    -449.0
8       NaN
9   -2019.0
Name: DAYS_EMPLOYED, dtype: float64

In [52]:
analytics_df['DAYS_EMPLOYED'].isna().sum()

np.int64(55374)

In [53]:
analytics_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 307511 entries, 0 to 307510
Data columns (total 20 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   SK_ID_CURR            307511 non-null  int64
 1   TARGET                307511 non-null  int64
 2   CODE_GENDER           307511 non-null  object
 3   DAYS_BIRTH            307511 non-null  int64
 4   DAYS_EMPLOYED         252137 non-null  float64
 5   AMT_INCOME_TOTAL      307511 non-null  float64
 6   AMT_CREDIT            307511 non-null  float64
 7   AMT_ANNUITY           307499 non-null  float64
 8   EXT_SOURCE_1          134133 non-null  float64
 9   EXT_SOURCE_2          306851 non-null  float64
 10  EXT_SOURCE_3          246546 non-null  float64
 11  total_bureau_records  263491 non-null  float64
 12  total_credit_sum      263491 non-null  float64
 13  total_debt            263491 non-null  float64
 14  total_overdue         263491 non-null  float64
 15  max_overdue           183886 non-null  float64
 16  total_previous_apps   291057 non-null  float64
 17  avg_prev_credit       291057 non-null  float64
 18  avg_prev_application  291057 non-null  float64
 19  AGE_YEARS             307511 non-null  float64
dtypes: float64(16), int64(3), object(1)
memory usage: 46.9+ MB

In [54]:
summary_cols = [
    'total_bureau_records',
    'total_credit_sum',
    'total_debt',
    'total_overdue',
    'max_overdue',
    'total_previous_apps',
    'avg_prev_credit',
    'avg_prev_application'
]

analytics_df[summary_cols] = analytics_df[summary_cols].fillna(0)

In [55]:
analytics_df.to_csv(
    "analytics_customer.csv",
    index=False
)

In [56]:
import os

os.path.exists("analytics_customer.csv")

True

In [57]:
import os

os.path.getsize("analytics_customer.csv") / (1024*1024)

44.72778511047363

In [58]:
analytics_df.dtypes

SK_ID_CURR                int64
TARGET                    int64
CODE_GENDER              object
DAYS_BIRTH                int64
DAYS_EMPLOYED           float64
AMT_INCOME_TOTAL        float64
AMT_CREDIT              float64
AMT_ANNUITY             float64
EXT_SOURCE_1            float64
EXT_SOURCE_2            float64
EXT_SOURCE_3            float64
total_bureau_records    float64
total_credit_sum        float64
total_debt              float64
total_overdue           float64
max_overdue             float64
total_previous_apps     float64
avg_prev_credit         float64
avg_prev_application    float64
AGE_YEARS               float64
dtype: object